preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:
  maven-local:

plugins:
  org.jetbrains.kotlin.jvm:
    alias: kotlin-jvm
    version: 2.2.10
  com.vanniktech.maven.publish:
    alias: maven-publish
    version: 0.34.0

libraries:
  com.squareup.okhttp3:
    okhttp:
      version: 5.1.0
  com.squareup:
    kotlinpoet:
      version: 2.2.0
    javapoet:
      version: 1.13.0
  net.lingala.zip4j:
    zip4j:
      version: 2.11.5